//Via: https://app.rize.education/courses/8156/resource/1f6287eb-b9a5-4052-9b8c-29e987b37a75?weekId=10972
import { useState } from 'react'
import './App.css'
import ProductCard from "./components/ProductCard.jsx";
import {Header} from "./components/Header.jsx";
import {Hero} from "./components/Hero.jsx";
import {Footer} from "./components/Footer.jsx";
import {CartItem} from "./components/CartItem.jsx";

function App() {

    const [cart, setCart] = useState([])

    function addToCart(id) {
        if(cart.indexOf(id) === -1) {
            setCart([...cart,id])
        }
    }

    function removeFromCart(id) {
        if(cart.indexOf(id) !== -1) {
            setCart(cart.toSpliced(cart.indexOf(id), 1))
        }
    }

    const products = [
        {
            id: 1,
            name: "Wireless Headphones",
            price: 99.99,
            image: "https://placehold.co/600x400",
            description: "Premium noise-cancelling headphones with 30-hour battery life"
        },
        {
            id: 2,
            name: "Smart Watch",
            price: 249.99,
            image: "https://placehold.co/600x400",
            description: "Fitness tracker with heart rate monitor and GPS"
        },
        {
            id: 3,
            name: "Bluetooth Speaker",
            price: 79.99,
            image: "https://placehold.co/600x400",
            description: "Portable waterproof speaker with 360-degree sound"
        },
        {
            id: 4,
            name: "Laptop Stand",
            price: 49.99,
            image: "https://placehold.co/600x400",
            description: "Ergonomic aluminum stand for laptops and tablets"
        },
        {
            id: 5,
            name: "Webcam",
            price: 129.99,
            image: "https://placehold.co/600x400",
            description: "4K webcam with auto-focus and noise reduction"
        },
        {
            id: 6,
            name: "Mechanical Keyboard",
            price: 159.99,
            image: "https://placehold.co/600x400",
            description: "RGB backlit keyboard with custom switches"
        }
    ];
    //Filler text generated by ChatGPT
    return (
      <div className="app">
          <Header items={cart}/>

          <main className="main-content">
              <Hero/>
              {products.map((product) => (
                  <ProductCard
                      key={product.id}
                      name={product.name}
                      price={product.price}
                      description={product.description}
                      image={product.image}
                      onClick={() => addToCart(product.id)}
                  />
              ))}
              <h2>Items in Cart:</h2>
              {cart.length > 0 ?
                  <>
                    {products.filter((product)=> {return cart.indexOf(product.id) !== -1}).map((product) => (
                      <CartItem
                          name={product.name}
                          price={product.price}
                          onClick={() => removeFromCart(product.id)}
                      />
                  ))}
                    <h3>Total price: ${products.filter((product)=> {return cart.indexOf(product.id) !== -1}).reduce((total, product) => total + product.price, 0).toFixed(2)
                    }</h3>
                  </>
                  :
                  <h3>There are no items in your cart</h3>
              }
          </main>

          <Footer/>
      </div>
  )
}


export default App
