//Via: https://app.rize.education/courses/8156/resource/1f6287eb-b9a5-4052-9b8c-29e987b37a75?weekId=10972
import {useEffect, useState} from 'react'
import './App.css'
import {Header} from "./components/Header.jsx";
import {Footer} from "./components/Footer.jsx";
import { BrowserRouter, Routes, Route, Link } from 'react-router-dom';
import {HomePage} from "./pages/HomePage.jsx";
import {ProductsPage} from "./pages/ProductsPage.jsx";
import {CartPage} from "./pages/CartPage.jsx";

function App() {


    const [cart, setCart] = useState(() => {
        const savedCart = localStorage.getItem('cart');
        return savedCart ? JSON.parse(savedCart) : [];
    })

    useEffect(() => {
        try {
            localStorage.setItem("cart", JSON.stringify(cart)); }
        catch {
            console.warn('Could not save cart to localStorage:');
        }
    },[cart])

    function addToCart(id) {
        if(cart.indexOf(id) === -1) {
            setCart([...cart,id])
        }
    }

    function removeFromCart(id) {
        if(cart.indexOf(id) !== -1) {
            setCart(cart.toSpliced(cart.indexOf(id), 1))
        }
    }

    const products = [
        {
            id: 1,
            name: "Wireless Headphones",
            price: 99.99,
            image: "https://placehold.co/600x400",
            description: "Premium noise-cancelling headphones with 30-hour battery life"
        },
        {
            id: 2,
            name: "Smart Watch",
            price: 249.99,
            image: "https://placehold.co/600x400",
            description: "Fitness tracker with heart rate monitor and GPS"
        },
        {
            id: 3,
            name: "Bluetooth Speaker",
            price: 79.99,
            image: "https://placehold.co/600x400",
            description: "Portable waterproof speaker with 360-degree sound"
        },
        {
            id: 4,
            name: "Laptop Stand",
            price: 49.99,
            image: "https://placehold.co/600x400",
            description: "Ergonomic aluminum stand for laptops and tablets"
        },
        {
            id: 5,
            name: "Webcam",
            price: 129.99,
            image: "https://placehold.co/600x400",
            description: "4K webcam with auto-focus and noise reduction"
        },
        {
            id: 6,
            name: "Mechanical Keyboard",
            price: 159.99,
            image: "https://placehold.co/600x400",
            description: "RGB backlit keyboard with custom switches"
        }
    ];
    //Filler text generated by ChatGPT
    return (
        <BrowserRouter>
            <div className="app">
                <Header items={cart}/>
                <main className="main-content">
                    <Routes>
                        <Route path="/" element={<HomePage/>}/>
                        <Route path="/products" element={<ProductsPage products={products} addToCart={addToCart}/>}/>
                        <Route path="/cart"
                               element={<CartPage cart={cart} products={products} removeFromCart={removeFromCart}/>}/>
                    </Routes>
                </main>
                <Footer/>
            </div>
        </BrowserRouter>
)
}


            export default App
